Repository plugwise/Plugwise-Smile, pull requests merged in 2020-04, with the labels that each got.

#15 Version bump & black
  Plugwise_Smile/Smile.py
  setup.py
  tests/test_Smile.py
Labels: enhancement

#16 Review
  .coverage
  .travis.yml
  Plugwise_Smile/Smile.py
  setup.py
  tests/test_Smile.py
Labels: bug, enhancement

#17 Public beta 0.1.0
  setup.py
Labels: enhancement

#18 v0.1.2 LINT, public use of variables, cleanup
  .coverage
  Plugwise_Smile/Smile.py
  setup.py
  tests/test_Smile.py
Labels: enhancement

#26 P1v3 full option
  .coverage
  Plugwise_Smile/Smile.py
  setup.py
  tests/README.md
  tests/p1v3_full_option/core.appliances.xml
  tests/p1v3_full_option/core.direct_objects.xml
  tests/p1v3_full_option/core.domain_objects.xml
  tests/p1v3_full_option/core.locations.xml
  tests/p1v3_full_option/core.modules.xml
  tests/test_Smile.py
Labels: bug, enhancement

#30 Fix central components
  .coverage
  Plugwise_Smile/Smile.py
  setup.py
  tests/test_Smile.py
Labels: bug, enhancement

#36 Added heatpump_cooling testdata and tests
  .coverage
  Plugwise_Smile/Smile.py
  setup.py
  tests/anna_heatpump_cooling/core.appliances.xml
  tests/anna_heatpump_cooling/core.direct_objects.xml
  tests/anna_heatpump_cooling/core.domain_objects.xml
  tests/anna_heatpump_cooling/core.locations.xml
  tests/anna_heatpump_cooling/core.modules.xml
  tests/test_Smile.py
Labels: enhancement

#37 Add schedule_temperature in data output
  .coverage
  Plugwise_Smile/Smile.py
  setup.py
  tests/test_Smile.py
Labels: enhancement

#38 Adjust code to handle FutureWarnings from #34
  .coverage
  Plugwise_Smile/Smile.py
  setup.py
Labels: enhancement

#41 Handle missing/timeout/otherwise XML data (both initial and in-flight)
  .coverage
  Plugwise_Smile/Smile.py
  setup.py
  tests/test_Smile.py
Labels: bug, enhancement

#43 Lintfix, DHW
  .coverage
  .travis.yml
  Plugwise_Smile/Smile.py
  pylintrc
  run_tests_and_coverage.sh
  setup.py
  tests/test_Smile.py
Labels: enhancement

#45 Improve testing and testing environment
  .coverage
  .coveragerc
  .flake8
  .gitignore
  .travis.yml
  Plugwise_Smile/Smile.py
  Plugwise_Smile/__init__.py
  requirements.txt
  run_tests_and_coverage.sh
  setup.py
  tests/README.md
  tests/requirements.txt
  tests/test_Smile.py
Labels: documentation, enhancement

#40 Release 0.2.0 - pylint mostly fixed - black
  .coverage
  Plugwise_Smile/Smile.py
  README.md
  setup.py
  tests/test_Smile.py
Labels: documentation, enhancement

#47 Possible fix for legacy anna smt
  .coverage
  Plugwise_Smile/Smile.py
  setup.py
  tests/test_Smile.py
Labels: bug
