Repository plugwise/Plugwise-Smile, pull requests merged in 2020-05, with the labels that each got.

#54 can we test this?
  Plugwise_Smile/Smile.py
Labels: enhancement, good first issue

#56 Version nr via __init__.py
  Plugwise_Smile/__init__.py
  setup.py
Labels: enhancement

#58 Updated tests
  .coverage
  pre-commit.sh
  tests/anna_without_boiler_fw3/core.appliances.xml
  tests/anna_without_boiler_fw3/core.direct_objects.xml
  tests/anna_without_boiler_fw3/core.domain_objects.xml
  tests/anna_without_boiler_fw3/core.locations.xml
  tests/anna_without_boiler_fw3/core.modules.xml
  tests/anna_without_boiler_fw4/core.appliances.xml
  tests/anna_without_boiler_fw4/core.direct_objects.xml
  tests/anna_without_boiler_fw4/core.domain_objects.xml
  tests/anna_without_boiler_fw4/core.locations.xml
  tests/anna_without_boiler_fw4/core.modules.xml
  tests/test_Smile.py
Labels: documentation

#61 Comment on users
  tests/README.md
Labels: documentation

#59 Remove useless water_pressure sensor
  Plugwise_Smile/Smile.py
  tests/test_Smile.py
Labels: enhancement

#57 Possible aiohttp improvement
  Plugwise_Smile/Smile.py
  Plugwise_Smile/__init__.py
Labels: enhancement

#64 Partial core review update
  Plugwise_Smile/Smile.py
  Plugwise_Smile/__init__.py
Labels: enhancement

#66 Implement basis for feature requested in #65
  Plugwise_Smile/Smile.py
  Plugwise_Smile/__init__.py
Labels: enhancement
